name: CI-CD.yml

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Start the application
        run: npm run start &
        env:
          NODE_ENV: test

      - name: Run Cypress tests
        run: npx cypress run